server:
  port: 8086
spring:
  application:
    name: sms-service
  rabbitmq:
    host: 192.168.25.128
    username: leyou
    password: leyou
    virtual-host: /leyou
leyou:
  sms:
    accessKeyId: LTAI4Fi3AKMjAbMc53pZvXku # 你自己的accessKeyId
    accessKeySecret: tcQU1aPKRSTOJ63pgRdNFQlWUihbq4 # 你自己的AccessKeySecret
    signName: 乐优商城 # 签名名称
    verifyCodeTemplate: SMS_186598126 # 模板名称