server:
  port: 8083
spring:
  jackson:
    default-property-inclusion: non_null # 配置json处理时忽略空值
  application:
    name: search-service
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 192.168.57.101:9300
  main:
    allow-bean-definition-overriding: true
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    register-with-eureka: false
    fetch-registry: true
  instance:
    lease-renewal-interval-in-seconds: 20 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 40 # 10秒不发送就过期
  ribbon:
    eureka:
      enabled: true
    ConnectTimeout: 10000 # ribbon链接超时时长
    ReadTimeout: 10000 # ribbon读取超时时间长
